### ISSUE TITLE
Typo on line 70 resulting in ignored forbid flag

### ISSUE THREAD

**Issue by Yoriz** [sbyrnes321/trianglesolver#1]
https://github.com/sbyrnes321/trianglesolver/blob/master/trianglesolver.py#L70
`elif ssa == 'forbid':`
should be
`elif ssa_flag == 'forbid':`

**Comment by sbyrnes321** [comment]
Fixed by 62f8696f0c2b5648a8e56e236c9b7da80f2d0c26 . New version 1.1 incorporates this change. Thank you!
