### ISSUE TITLE
Issue With Ambiguous Case

### ISSUE THREAD

**Issue by Gordon24771402** [sbyrnes321/trianglesolver#2]
An excellent program! I am completing my precalculus homework with it! 
**Issue:**
The error came when trying to solve an ambiguous case with the Law of Sines.
However, angle C is actually 29° since the 151° can be eliminated.
![Issue0001](https://user-images.githubusercontent.com/63176281/78857745-d35eb280-7a5c-11ea-8fba-5dd0b461d4f5.png)

**Comment by sbyrnes321** [comment]
Why can the 151° be eliminated?

**Comment by Gordon24771402** [comment]
> Why can the 151° be eliminated?

Otherwise, 151°+88°(∠C+∠A) will be greater than 180°, which is impossible in a triangle.

**Comment by sbyrnes321** [comment]
Oh, you're right.

**Comment by sbyrnes321** [comment]
This happens whenever you have A, a, b with b<a, correct? Just off the top of my head.

**Comment by Gordon24771402** [comment]
YES! With one more condition satisfied: **∠A < 90°**

**Comment by sbyrnes321** [comment]
Would you mind checking that the latest version fixes the problem?

**Comment by Gordon24771402** [comment]
> Would you mind checking that the latest version fixes the problem?

The latest version has fixed the problem! Only 29.381... now! Great! Thank you!

**Comment by sbyrnes321** [comment]
Now fixed in version 1.2. Thanks again!
